"""add apply_log table

Revision ID: 03d3d0cc6aed
Revises: f1d8e212e1f4
Create Date: 2026-08-29 10:17:45.701414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d3d0cc6aed'
down_revision: Union[str, None] = 'f1d8e212e1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apply_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal', sa.String(length=50), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apply_log_applied_date'), 'apply_log', ['applied_date'], unique=False)
    op.create_index(op.f('ix_apply_log_id'), 'apply_log', ['id'], unique=False)
    op.create_index(op.f('ix_apply_log_portal'), 'apply_log', ['portal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apply_log_portal'), table_name='apply_log')
    op.drop_index(op.f('ix_apply_log_id'), table_name='apply_log')
    op.drop_index(op.f('ix_apply_log_applied_date'), table_name='apply_log')
    op.drop_table('apply_log')
    # ### end Alembic commands ###
